//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: messages_robocup_ssl_geometry.proto
namespace messages_robocup_ssl_geometry
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector2f")]
  public partial class Vector2f : global::ProtoBuf.IExtensible
  {
    public Vector2f() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SSL_FieldLineSegment")]
  public partial class SSL_FieldLineSegment : global::ProtoBuf.IExtensible
  {
    public SSL_FieldLineSegment() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private Vector2f _p1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"p1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vector2f p1
    {
      get { return _p1; }
      set { _p1 = value; }
    }
    private Vector2f _p2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"p2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vector2f p2
    {
      get { return _p2; }
      set { _p2 = value; }
    }
    private float _thickness;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"thickness", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float thickness
    {
      get { return _thickness; }
      set { _thickness = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SSL_FieldCicularArc")]
  public partial class SSL_FieldCicularArc : global::ProtoBuf.IExtensible
  {
    public SSL_FieldCicularArc() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private Vector2f _center;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"center", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vector2f center
    {
      get { return _center; }
      set { _center = value; }
    }
    private float _radius;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"radius", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float radius
    {
      get { return _radius; }
      set { _radius = value; }
    }
    private float _a1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"a1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float a1
    {
      get { return _a1; }
      set { _a1 = value; }
    }
    private float _a2;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"a2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float a2
    {
      get { return _a2; }
      set { _a2 = value; }
    }
    private float _thickness;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"thickness", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float thickness
    {
      get { return _thickness; }
      set { _thickness = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SSL_GeometryFieldSize")]
  public partial class SSL_GeometryFieldSize : global::ProtoBuf.IExtensible
  {
    public SSL_GeometryFieldSize() {}
    
    private int _field_length;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"field_length", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int field_length
    {
      get { return _field_length; }
      set { _field_length = value; }
    }
    private int _field_width;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"field_width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int field_width
    {
      get { return _field_width; }
      set { _field_width = value; }
    }
    private int _goal_width;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"goal_width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goal_width
    {
      get { return _goal_width; }
      set { _goal_width = value; }
    }
    private int _goal_depth;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"goal_depth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goal_depth
    {
      get { return _goal_depth; }
      set { _goal_depth = value; }
    }
    private int _boundary_width;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"boundary_width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int boundary_width
    {
      get { return _boundary_width; }
      set { _boundary_width = value; }
    }
    private readonly global::System.Collections.Generic.List<SSL_FieldLineSegment> _field_lines = new global::System.Collections.Generic.List<SSL_FieldLineSegment>();
    [global::ProtoBuf.ProtoMember(6, Name=@"field_lines", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSL_FieldLineSegment> field_lines
    {
      get { return _field_lines; }
    }
  
    private readonly global::System.Collections.Generic.List<SSL_FieldCicularArc> _field_arcs = new global::System.Collections.Generic.List<SSL_FieldCicularArc>();
    [global::ProtoBuf.ProtoMember(7, Name=@"field_arcs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSL_FieldCicularArc> field_arcs
    {
      get { return _field_arcs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SSL_GeometryCameraCalibration")]
  public partial class SSL_GeometryCameraCalibration : global::ProtoBuf.IExtensible
  {
    public SSL_GeometryCameraCalibration() {}
    
    private uint _camera_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"camera_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint camera_id
    {
      get { return _camera_id; }
      set { _camera_id = value; }
    }
    private float _focal_length;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"focal_length", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float focal_length
    {
      get { return _focal_length; }
      set { _focal_length = value; }
    }
    private float _principal_point_x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"principal_point_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float principal_point_x
    {
      get { return _principal_point_x; }
      set { _principal_point_x = value; }
    }
    private float _principal_point_y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"principal_point_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float principal_point_y
    {
      get { return _principal_point_y; }
      set { _principal_point_y = value; }
    }
    private float _distortion;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"distortion", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float distortion
    {
      get { return _distortion; }
      set { _distortion = value; }
    }
    private float _q0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"q0", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float q0
    {
      get { return _q0; }
      set { _q0 = value; }
    }
    private float _q1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"q1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float q1
    {
      get { return _q1; }
      set { _q1 = value; }
    }
    private float _q2;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"q2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float q2
    {
      get { return _q2; }
      set { _q2 = value; }
    }
    private float _q3;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"q3", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float q3
    {
      get { return _q3; }
      set { _q3 = value; }
    }
    private float _tx;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"tx", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float tx
    {
      get { return _tx; }
      set { _tx = value; }
    }
    private float _ty;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"ty", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ty
    {
      get { return _ty; }
      set { _ty = value; }
    }
    private float _tz;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"tz", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float tz
    {
      get { return _tz; }
      set { _tz = value; }
    }

    private float _derived_camera_world_tx = default(float);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"derived_camera_world_tx", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float derived_camera_world_tx
    {
      get { return _derived_camera_world_tx; }
      set { _derived_camera_world_tx = value; }
    }

    private float _derived_camera_world_ty = default(float);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"derived_camera_world_ty", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float derived_camera_world_ty
    {
      get { return _derived_camera_world_ty; }
      set { _derived_camera_world_ty = value; }
    }

    private float _derived_camera_world_tz = default(float);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"derived_camera_world_tz", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float derived_camera_world_tz
    {
      get { return _derived_camera_world_tz; }
      set { _derived_camera_world_tz = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SSL_GeometryData")]
  public partial class SSL_GeometryData : global::ProtoBuf.IExtensible
  {
    public SSL_GeometryData() {}
    
    private SSL_GeometryFieldSize _field;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"field", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public SSL_GeometryFieldSize field
    {
      get { return _field; }
      set { _field = value; }
    }
    private readonly global::System.Collections.Generic.List<SSL_GeometryCameraCalibration> _calib = new global::System.Collections.Generic.List<SSL_GeometryCameraCalibration>();
    [global::ProtoBuf.ProtoMember(2, Name=@"calib", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSL_GeometryCameraCalibration> calib
    {
      get { return _calib; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}