//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MRL.SSL.CommonClasses.MathLibrary;
namespace MRL.SSL.GameDefinitions.General_Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class ActiveRoleSettings : global::System.Configuration.ApplicationSettingsBase
    {

        private static ActiveRoleSettings defaultInstance = ((ActiveRoleSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ActiveRoleSettings())));

        public static ActiveRoleSettings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public SerializableDictionary<int, ActiveRoleSettingTemplate> Parameters
        {
            get
            {
                return ((SerializableDictionary<int, ActiveRoleSettingTemplate>)(this["Parameters"]));
            }
            set
            {
                this["Parameters"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KickPolicy
        {
            get
            {
                return ((int)(this["KickPolicy"]));
            }
            set
            {
                this["KickPolicy"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConfilictPolicy
        {
            get
            {
                return ((int)(this["ConfilictPolicy"]));
            }
            set
            {
                this["ConfilictPolicy"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainPolicy
        {
            get
            {
                return ((int)(this["MainPolicy"]));
            }
            set
            {
                this["MainPolicy"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DangerZoneDist
        {
            get
            {
                return ((double)(this["DangerZoneDist"]));
            }
            set
            {
                this["DangerZoneDist"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DangerAreaX
        {
            get
            {
                return ((double)(this["DangerAreaX"]));
            }
            set
            {
                this["DangerAreaX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KickPower
        {
            get
            {
                return ((double)(this["KickPower"]));
            }
            set
            {
                this["KickPower"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSpinBackWard
        {
            get
            {
                return ((bool)(this["IsSpinBackWard"]));
            }
            set
            {
                this["IsSpinBackWard"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinGoodness
        {
            get
            {
                return ((double)(this["MinGoodness"]));
            }
            set
            {
                this["MinGoodness"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KickAwayInField
        {
            get
            {
                return ((bool)(this["KickAwayInField"]));
            }
            set
            {
                this["KickAwayInField"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Chip
        {
            get
            {
                return ((bool)(this["Chip"]));
            }
            set
            {
                this["Chip"] = value;
            }
        }
    }
}
