//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRL.SSL.GameDefinitions.General_Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class GameSettings : global::System.Configuration.ApplicationSettingsBase
    {

        private static GameSettings defaultInstance = ((GameSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GameSettings())));

        public static GameSettings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::MRL.SSL.CommonClasses.MathLibrary.SerializableDictionary<string, string> Technique
        {
            get
            {
                return ((global::MRL.SSL.CommonClasses.MathLibrary.SerializableDictionary<string, string>)(this["Technique"]));
            }
            set
            {
                this["Technique"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList DribleState
        {
            get
            {
                return ((global::System.Collections.ArrayList)(this["DribleState"]));
            }
            set
            {
                this["DribleState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::MRL.SSL.CommonClasses.MathLibrary.SerializableDictionary<int, Engines> Engines
        {
            get
            {
                return ((global::MRL.SSL.CommonClasses.MathLibrary.SerializableDictionary<int, Engines>)(this["Engines"]));
            }
            set
            {
                this["Engines"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringDictionary Robots
        {
            get
            {
                return ((global::System.Collections.Specialized.StringDictionary)(this["Robots"]));
            }
            set
            {
                this["Robots"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::MRL.SSL.CommonClasses.MathLibrary.SerializableDictionary<string, int> Tactic
        {
            get
            {
                return ((global::MRL.SSL.CommonClasses.MathLibrary.SerializableDictionary<string, int>)(this["Tactic"]));
            }
            set
            {
                this["Tactic"] = value;
            }
        }
    }
}
