//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MRL.SSL.GameDefinitions.Visualizer_Classes;
namespace MRL.SSL.GameDefinitions.General_Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class LookUpTable : global::System.Configuration.ApplicationSettingsBase
    {

        private static LookUpTable defaultInstance = ((LookUpTable)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LookUpTable())));

        public static LookUpTable Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::MRL.SSL.CommonClasses.MathLibrary.SerializableDictionary<string, double> DirectKick
        {
            get
            {
                return ((global::MRL.SSL.CommonClasses.MathLibrary.SerializableDictionary<string, double>)(this["DirectKick"]));
            }
            set
            {
                this["DirectKick"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::MRL.SSL.CommonClasses.MathLibrary.SerializableDictionary<int, ChipKick> ChipKick
        {
            get
            {
                return ((global::MRL.SSL.CommonClasses.MathLibrary.SerializableDictionary<int, ChipKick>)(this["ChipKick"]));
            }
            set
            {
                this["ChipKick"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::MRL.SSL.CommonClasses.MathLibrary.SerializableDictionary<int, MetricChipKick> MetricChipKick
        {
            get
            {

               // return null;
                return ((global::MRL.SSL.CommonClasses.MathLibrary.SerializableDictionary<int, MetricChipKick>)(this["MetricChipKick"]));
            }
            set
            {
                this["MetricChipKick"] = value;
            }
        }
    }
}
