//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRL.SSL.GameDefinitions.General_Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class MainGameParameters : global::System.Configuration.ApplicationSettingsBase
    {

        private static MainGameParameters defaultInstance = ((MainGameParameters)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MainGameParameters())));

        public static MainGameParameters Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double CornerDistance
        {
            get
            {
                return ((double)(this["CornerDistance"]));
            }
            set
            {
                this["CornerDistance"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.08")]
        public double BallMovementToActive
        {
            get
            {
                return ((double)(this["BallMovementToActive"]));
            }
            set
            {
                this["BallMovementToActive"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Drawing
        {
            get
            {
                return ((bool)(this["Drawing"]));
            }
            set
            {
                this["Drawing"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double kPfront
        {
            get
            {
                return ((double)(this["kPfront"]));
            }
            set
            {
                this["kPfront"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double kdfront
        {
            get
            {
                return ((double)(this["kdfront"]));
            }
            set
            {
                this["kdfront"] = value;
            }
        }
    }
}
