//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
namespace MRL.SSL.GameDefinitions.General_Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class RegionScore : global::System.Configuration.ApplicationSettingsBase {
        
        private static RegionScore defaultInstance = ((RegionScore)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RegionScore())));
        
        public static RegionScore Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SigmaX {
            get {
                return ((double)(this["SigmaX"]));
            }
            set {
                this["SigmaX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SigmaY {
            get {
                return ((double)(this["SigmaY"]));
            }
            set {
                this["SigmaY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public Dictionary<int, float[,]> Scores
        {
            get {
                return ((Dictionary<int, float[,]>)(this["Scores"]));
            }
            set {
                this["Scores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public List<Score> Data
        {
            get {
                return ((List<Score>)(this["Data"]));
            }
            set {
                this["Data"] = value;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SigmaXt
        {
            get
            {
                return ((double)(this["SigmaXt"]));
            }
            set
            {
                this["SigmaXt"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SigmaYt
        {
            get
            {
                return ((double)(this["SigmaYt"]));
            }
            set
            {
                this["SigmaYt"] = value;
            }
        }
    }
}
