//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRL.SSL.GameDefinitions.General_Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class SimulatorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SimulatorSettings defaultInstance = ((SimulatorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SimulatorSettings())));
        
        public static SimulatorSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
