//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRL.SSL.GameDefinitions.General_Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class VisualizerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static VisualizerSettings defaultInstance = ((VisualizerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VisualizerSettings())));
        
        public static VisualizerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogUseDefaultName {
            get {
                return ((bool)(this["LogUseDefaultName"]));
            }
            set {
                this["LogUseDefaultName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogUseDefaultAddress {
            get {
                return ((bool)(this["LogUseDefaultAddress"]));
            }
            set {
                this["LogUseDefaultAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("userFileName")]
        public string LogUserFileName {
            get {
                return ((string)(this["LogUserFileName"]));
            }
            set {
                this["LogUserFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/")]
        public string LogUserLogAddress {
            get {
                return ((string)(this["LogUserLogAddress"]));
            }
            set {
                this["LogUserLogAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LoggerDelay {
            get {
                return ((int)(this["LoggerDelay"]));
            }
            set {
                this["LoggerDelay"] = value;
            }
        }
    }
}
